### PR TITLE
we need to make sure the object DOESNT have an objectid

### PR DESCRIPTION
**Pull request by jgravois**
no comment.

cc/ @nixta

### CODE REVIEW

**Comment by nixta** [comment]
Hmmm. Then don't you want `if (!record.hasOwnProperty('OBJECTID') || record.OBJECTID == 0)`?

I thought we were meant to be saying "If we don't have an OBJECTID, or if we do but it's 0, then let's set it to `optionalId`, otherwise, we'll just leave it as is", right?

**Comment by jgravois** [comment]
close.  if we don't have an OBJECTID at all, lets set it to `optionalId`.  if we *do* have an OBJECTID and the value is set `0`, do **not** accidently override it with `optionalId`.

**Comment by jgravois** [comment]
reading what i just typed, i guess the second check is pretty much entirely redundant...

**Comment by nixta** [comment]
Right. I was about to ask.

So any value in OBJECTID is valid, but if nothing's been set, then use optionId?

**Comment by jgravois** [comment]
i couldnt feel better about the name of my feature branch.

**Comment by nixta** [comment]
:)

**Pull request merged**
